services:

  mongodb:
    image: mongo
    container_name: autoskola-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    container_name: autoskola-server
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb+srv://autoskoladmin:autoskola@autoskoladb.cmfvtk2.mongodb.net/autoskola
      JWT_SECRET: secret

  client:
    build: ./client
    container_name: autoskola-client
    ports:
      - "5173:5173"
    depends_on:
      - server

volumes:
  mongo-data: